### ISSUE TITLE
8-2019-q3 URL is gone or changed

### ISSUE THREAD

**Issue by HotelCalifornia** [osx-cross/homebrew-arm#13] opened 2019-11-06 01:08 UTC
When attempting to install the toolchain:

```
brew tap osx-cross/arm && brew install arm-gcc-bin
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Installing arm-gcc-bin from osx-cross/arm
==> Downloading https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-mac.tar.bz2
==> Downloading from https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-mac.tar.bz2

curl: (22) The requested URL returned error: 404 The specified blob does not exist.
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "arm-gcc-bin"
Download failed: https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-mac.tar.bz2
```

**Comment by ladislas** [comment] 2019-11-06 09:36
Thanks for reporting @HotelCalifornia -- this is a duplicate of #12 

work around is to use the ARM mbed formula: https://github.com/ARMmbed/homebrew-formulae

**Closed as completed by ladislas** 2019-11-06 09:36 UTC

**Comment by ladislas** [comment] 2019-11-16 14:21
@HotelCalifornia everything is back to normal, ARM fixed the missing links issue.
